### ISSUE TITLE
Remove dependency on firebase

### ISSUE THREAD

**Issue by flmn** [oxequa/flutter_cache_image#5]
As a image utility, why this plugin depend on firebase?

When run on iOS, it crashed.

The log shows: 
Configuring the default Firebase app...
*** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'

**Comment by m-j-g** [comment]
because it supports retrieving images from firebase.

**Comment by flmn** [comment]
ok.
